name: Create Release Zip

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
    - name: Set up environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "RELEASE_TITLE=$(date +'%Y.%m.%d') 词库更新" >> $GITHUB_ENV

    - name: Checkout main branch
      uses: actions/checkout@v4
        
    - name: Zip main branch files excluding .git and .github
      run: zip -r xmjd6.zip . -x "*.git*" -x "*.github*" -x "yong*" -x "mb*" -x "Rime*"

    - name: Create Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CURRENT_DATE }}
        release_name: ${{ env.RELEASE_TITLE }}
        body: |
          ## Release Notes
          - [如何使用](https://github.com/hugh7007/xmjd6-rere#如何使用)
        draft: false
        prerelease: false
        
    - name: Upload xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./xmjd6.zip
        asset_name: xmjd6.zip
        asset_content_type: application/zip
